### ISSUE TITLE
GetJobRequest setLocation do not working

### ISSUE THREAD

**Issue by georgenov** [googleapis/java-dataflow#135]
When I'm trying to perform `GetJobRequest` - `setLocation` seems to not work.
I was able to get a Dataflow job in the `us-central1` location, because as far as I understand - it is the default location.

But I'm not able to get Dataflow jobs that are in another location. Just getting a Not Found response.

**Comment by davidcavazos** [comment]
Hearing back from the product team, this issue should now be fixed on the latest version of the library.

I'm closing this, but feel free to re-open if the problem still persists.
